#!/bin/bash

AMI_ID="ami-0084a47cc718c111a"
INSTANCE_TYPE="t2.medium"
KEY_NAME="jb"
SECURITY_GROUP_ID="sg-0990ccbf614dd262e"
SUBNET_ID="subnet-0f3992ae46877737a"
 
instanceNames=("nabil-m1" "nabil-m2" "nabil-DB")

for instanceName in "${instanceNames[@]}"; do
    INSTANCE_ID=$(aws ec2 run-instances \
        --image-id "$AMI_ID" \
        --instance-type "$INSTANCE_TYPE" \
        --key-name "$KEY_NAME" \
        --security-group-ids "$SECURITY_GROUP_ID" \
        --subnet-id "$SUBNET_ID" \
        --tag-specifications "ResourceType=instance,Tags=[{Key=Name,Value=${instanceName}}]" \
        --query 'Instances[0].InstanceId' \
        --output text)
 
    aws ec2 wait instance-running --instance-ids "$INSTANCE_ID"
 
    PUBLIC_IP=$(aws ec2 describe-instances \
        --instance-ids "$INSTANCE_ID" \
        --query 'Reservations[0].Instances[0].PublicIpAddress' \
        --output text)
 
    echo "$PUBLIC_IP"

done
 
 
